version: 2

sources:
  - name: staging
    database: book-recommendation-424220
    schema: goodreads_staging
    tables:
      - name: goodreads_book_series
      - name: goodreads_book_authors
models:
  - name: series
    description: "Franquia de livros"
    columns:
      - name: id
        description: "ID da franquia"
        data_type: numeric
      - name: title
        description: "Nome da franquia"
        data_type: string
  - name: authors
    description: "Autores dos livros"
    columns:
      - name: id
        description: "ID do autor"
        data_type: numeric
      - name: name
        description: "Nome do autor"
        data_type: string